# Generated by Django 4.2.4 on 2024-04-28 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[(None, 'None'), ('submitted', 'Submitted'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('private', models.JSONField(default=dict)),
                ('deposit', models.JSONField(default=dict)),
                ('waitlist_position', models.IntegerField(blank=True, null=True)),
                ('application_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
